### ISSUE TITLE
Anything to Contribute?

### ISSUE THREAD

**Issue by mriganka56** [dsc-iem/DermAssistApp-Hacktoberfest22#1]
Hi @Soham-Chakraborty-8455 
I would like to contribute to your project as I liked it.

Is there any way I can help with my contribution?

**Comment by Soham-Chakraborty-8455** [comment]
Yeah sure,
My repo would be live by 17th October.You can surely contribute henceforth.

**Comment by arpanghosh2416** [comment]
If you allow me to contribute on your project I will gladly do it as well. @Soham-Chakraborty-8455

**Comment by Soham-Chakraborty-8455** [comment]
My Project is live and ready to accept contributions now. Feel free to contribute to the issues. Happy Contributing !!!
