### ISSUE TITLE
Login and Signup Page designs for app

### ISSUE THREAD

**Issue by Soham-Chakraborty-8455** [dsc-iem/DermAssistApp-Hacktoberfest22#10]

**Comment by Night3y3** [comment]
Like the Sign In and Sign Up pages for the old and new users respectively. If Yes provide a grounded layout like a color pallet(With its code) and design to work on.

**Comment by Soham-Chakraborty-8455** [comment]
Okay, will provide it by tomorrow.

**Comment by Soham-Chakraborty-8455** [comment]
Login and SignUP Page designs:

**Comment by Soham-Chakraborty-8455** [comment]
Login Page
![Login Page](https://user-images.githubusercontent.com/93662806/197356752-0503a42e-c1d1-4c25-a619-d3d87950cea9.png)

**Comment by Soham-Chakraborty-8455** [comment]
Signup Page
![Signup page](https://user-images.githubusercontent.com/93662806/197356767-a6ae1639-2760-486c-b84f-35a02f6218c0.png)

**Comment by Night3y3** [comment]
Ok will work on it
