### ISSUE TITLE
In 3. Scan Image section of drawer, get access to phone's camera 

### ISSUE THREAD

**Issue by Soham-Chakraborty-8455** [dsc-iem/DermAssistApp-Hacktoberfest22#5]
https://user-images.githubusercontent.com/93662806/196027085-2837462b-54a6-4c14-8361-ac57cb567df3.mp4

Open Camera on Tap of 3. Scan Image (MENTIONED IN TODO)  in lib/Drawer.dart file

**Comment by VSB14** [comment]
Hii @Soham-Chakraborty-8455 , the attached clip intrigued me about the project, could you specify how I can contribute to this project?

**Comment by Soham-Chakraborty-8455** [comment]
The video shows the drawer page. Once the container named '3. Scan Image' is clicked/tapped, the phone's camera should pop up and start scanning the skin. In other words, I want the phone camera to startup once the '3. Scan Image' is pressed

**Comment by Manas0109** [comment]
hey, I am interested in this issue. Could you assign it to me?

**Comment by Soham-Chakraborty-8455** [comment]
Sure

**Comment by Justin-roy** [comment]
I already solve this please check pr issue #9.please assign me this task

**Comment by Soham-Chakraborty-8455** [comment]
Sure
