### ISSUE TITLE
Open Gallery for image selection when '2. Upload from Gallery' is clicked

### ISSUE THREAD

**Issue by Soham-Chakraborty-8455** [dsc-iem/DermAssistApp-Hacktoberfest22#7]
https://user-images.githubusercontent.com/93662806/196053219-a25eeb99-0b18-4e97-a5c6-57baa8edb722.mp4

When the '2. Upload from Gallery' is clicked/tapped in lib/drawer.dart section, a choose image from gallery option must pop-up allowing the user to choose images from the gallery and upload it for image scanning.

**Comment by harsh0620** [comment]
Hi @Soham-Chakraborty-8455, Please assign me this task. I can solve the issue.

**Comment by Soham-Chakraborty-8455** [comment]
Sure

**Comment by Justin-roy** [comment]
Hi @Soham-Chakraborty-8455, Please assign me also this task. I will solve this issue.

**Comment by Soham-Chakraborty-8455** [comment]
Okay

**Comment by nikhilvashisht** [comment]
Hey @Soham-Chakraborty-8455 ! I would like to open a pr to this issue. Please assign this to me.
